// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vohynmszdhiaivzwnwkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvaHlubXN6ZGhpYWl2endud2tjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMjQ5OTYsImV4cCI6MjA1ODgwMDk5Nn0.sLbrEW3ZngWD1B7QjXB92xD0ID5G4z-rIM59GOxKT6Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);